// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyfiyuewuyxqfqivpwxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5Zml5dWV3dXl4cWZxaXZwd3hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MzM4NjUsImV4cCI6MjA1OTUwOTg2NX0.td03F221gkJkcPbiDEvhCt6c1Bf5l58Ur14umIYgFn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);